title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: false
theme: jekyll-theme-cayman

conference_name: The 2nd Workshop on Recommendation with Generative Models
conference_www: "on the Web Conference 2024 (WWW'24)"
# conference_www: "Venue & Date: TBD"
conference_venue: "Singapore, Monday 13 - Friday 17 May 2024"
# conference_venue: ""
# conference_intro: "Will be held in 2024"
conference_intro: ""

github:
  zip_url: http://www.google.com

collections:
  organizers:
    output: true
  speakers:
    output: true
